plugins:
  slack_enabled:
    default: false
  slack_incoming_webhook_token:
    default: replace-with-wehbook-token
  slack_outbound_webhook_url:
    default: your-url-here
  slack_discourse_username:
