plugins:
  slack_enabled:
    default: false
    client: true
  slack_bot_token:
    default: your-bot-token-here
    client: true
  slack_webhook_token:
    default: replace-with-wehbook-token
  slack_discourse_username:
